<?php

namespace Bfxmpl\Bundle\BudgetBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CompteComptableRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompteComptableRepository extends EntityRepository
{
}
